### ISSUE TITLE
Invoke-WebFileRequest.ps1 fails for nasm

### ISSUE THREAD

**Issue by foopoiuyt** [WebKitForWindows/powershell-webkit-dev#8]
When attempting to use Install-Nasm, it gets a url "http://www.nasm.us/pub/nasm/releasebuilds/2.14
/win64/nasm-2.14-win64.zip" which it attempts to download with Invoke-WebFileRequest. This apparently then sets the SecurityProtocol to 0 which then causes the DownloadFile request to fail with "The underlying connection was closed: An unexpected error occurred on a receive."

**Comment by donny-dont** [comment]
I'm assuming this was fixed by #9
